apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: quorum
# kubectl explain rmq.spec
spec:
  # https://hub.docker.com/_/rabbitmq?tab=tags
  image: rabbitmq:3.8.9-management
  replicas: 3
  resources:
    limits:
      memory: 2Gi
      cpu: 1
    requests:
      memory: 2Gi
      cpu: 1
  persistence:
    storage: 10Gi
  rabbitmq:
    additionalConfig:
      total_memory_available_override_value = 2GiB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-rabbitmq-perf-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quorum-rabbitmq-perf-test
  template:
    metadata:
      labels:
        app: quorum-rabbitmq-perf-test
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: perftest
        # https://hub.docker.com/r/pivotalrabbitmq/perf-test/tags
        image: pivotalrabbitmq/perf-test:2.12.0
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        command:
          - /bin/bash
          - -c
        args:
          - |-
            bin/runjava com.rabbitmq.perf.PerfTest \
              --uri "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_SERVICE:5672/%2f"
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: quorum-rabbitmq-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: quorum-rabbitmq-default-user
              key: password
        - name: RABBITMQ_SERVICE
          value: quorum-rabbitmq-client
        - name: PRODUCERS
          value: "2"
        - name: VARIABLE_RATE
          value: "10:30,60:30,20:30,0:60"
        - name: CONFIRM
          value: "10"
        - name: CONSUMERS
          value: "4"
        - name: CONSUMER_LATENCY
          value: "100000"
        - name: AUTO_DELETE
          value: "false"
        - name: JSON_BODY
          value: "true"
        - name: SIZE
          value: "1000"
        - name: QOS
          value: "100"
        - name: MULTI_ACK_EVERY
          value: "10"
        - name: QUEUE_PATTERN
          value: "quorum-%d"
        - name: QUEUE_PATTERN_FROM
          value: "1"
        - name: QUEUE_PATTERN_TO
          value: "3"
        - name: QUEUE_ARGS
          value: "x-max-length=10000,x-queue-type=quorum,x-max-in-memory-bytes=500000000"
        - name: FLAG
          value: "persistent"
        - name: ROUTING_KEY
          value: "quorum"
        - name: METRICS_PROMETHEUS
          value: "true"
